Sharqiya
MohamadGT/training pull request #3
Opened 2020-02-11 13:25 UTC by MohamadGT

2020-02-12 13:38 UTC, RawanMoukalled reviewed
Can you please remove your grid-exercise files from this PR

2020-02-12 19:55 UTC, RawanMoukalled requested changes
Nice job with the file structure 👍

2020-02-12 19:55 UTC, RawanMoukalled commented on sharqiya/src/css/event-card.scss
> +.event-card__img_is-favorit {
The way favorites are currently done can be much smaller and cleaner. We'll want DRY (Don't Repeat Yourself) our code. 
1. Since all `event-card__img` modifiers are `position: relative`, we can just add this to `event-card__img` itself.
2. We can also place the shared properties in `event-card__img::after`, which are basically all the properties except background-color and background-image.
You can default background-color to #FFF and and the background-image to the unfavorited icon without the plus. 
3. Let's add a `is-favorited` modifier that just changes the background-color to orange 
4. We add a modifier for the icon type. Since we default to the heart without plus, we just add one more modifier, something like `heart-icon_checked`

That way, your html will be a combination of `event-card__img event-card__img_is-favorited event-card__img_heart-icon_checked`

2020-02-17 14:07 UTC, RawanMoukalled reviewed
Let's also make sure that all links/buttons/anything hoverable has the cursor change to a pointer (and if not add `cursor: pointer`.
Links like `Browse Events` should change to orange on hover, same for event chips (background still white, text orange)

2020-02-17 15:47 UTC, khaledsayyed requested changes

2020-02-17 15:47 UTC, khaledsayyed commented on sharqiya/src/css/calendar-tab.scss
> +}
Forgotten empty media queries.

2020-02-17 15:47 UTC, khaledsayyed commented on sharqiya/src/css/event-card.scss
> +  overflow: hidden;
Why do we need `overflow: hidden;`?

2020-02-17 15:47 UTC, khaledsayyed commented on sharqiya/src/css/event-card.scss
> +.event-card__data_has-favorit {
Did you mean `favorite`?

2020-02-17 15:47 UTC, khaledsayyed commented on sharqiya/src/css/events.scss
> +  // margin-top: 45px;
forgotten

2020-02-17 17:13 UTC, MohamadGT commented on sharqiya/src/css/social-media-icon.scss
> +.social-media-icon_color-gray {
let's export the icons with the border and background-color from the design.

2020-02-17 17:13 UTC, MohamadGT commented on sharqiya/src/css/sub-header.scss
> +  /* border-bottom: 1px solid rgba(230, 230, 230, .4); */
forgotten

2020-02-17 17:13 UTC, MohamadGT commented on sharqiya/src/event.html
> +        <div class="separator"></div>
let's add a margin for the heart button instead (use a modifier).

2020-02-17 17:13 UTC, MohamadGT commented on sharqiya/src/event.html
> +            <a class="link-to__link-short-text" href="">more</a>
Let's display this on tablet too.

2020-02-17 17:13 UTC, MohamadGT commented on sharqiya/src/event.html
> +        <img src="/src/assets/twitter-icon.svg" alt="" class="social-media-icon__img">
let's use css `background-url` and add modifiers for the icons.

2020-02-19 01:47 UTC, khaledsayyed requested changes

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +      <div class="footer__copy-rights">© 2012 - 2019. All rights reserved.</div>
s/`copy-rights`/`copyright`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +
Extra line.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  top: 0px;
s/`0px`/`0`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  z-index: 1;
Why do we need this?

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  &:hover {
Add an empty line above.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  &:hover {
Add an empty line above.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  &:hover {
Add an empty line above.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/index.html
> +        <button class="header__add-event">add event</button>
We need to use `type="button"`, the default is "submit".

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  cursor: pointer;
`cursor: pointer;` is the default for buttons, no need to add it here.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +        <a href="" class="header__language">بالعربية</a>
`href="javascript:void(0)"`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +        <a href="" class="header__login">login</a>
`href="javascript:void(0)"`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  .header_is-hidden {
s/`is-hidden`/`is-hidden-on-mobile`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +    box-sizing: border-box;
This should be in the main selector outside the media query.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +    align-items: center;
The above two properties are repeated (here and outside the media query).

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +    margin: 0 auto;
Same, we don't need this here, it's the default for `header__container`. Only add the properties you want to change inside the media query. We only need to specify the padding here, all of the other properties are exactly the same as the ones in the main selector.
It could be a better idea to use the media query inside the main selector. Ex:
```
.header__container {
  display: flex;
  align-items: center;
  max-width: 1282px;
  height: 68px;
  margin: 0 auto;

  @media (max-width: 749px) {
    padding: 14px;
  }
}
```
This way it's easier to check which properties you need to use inside the media query.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +@media (min-width: 1024px) {
You didn't address this comment.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/event-details.scss
> +
Extra line

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/header.scss
> +  }
```
  .header__browse-event,
  .header__location,
  .header__login,
  .header__add-event,
  .header__language {
    display: none;
  }
```

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/related-events.scss
> +  margin: 0 auto;
This doesn't do anything if the width is 100%/

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/related-events.scss
> +  .related-event__events > * {
You forgot to address this.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/related-events.scss
> +  .related-event__events > *:first-child {
And this.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/related-events.scss
> +  .related-event__events > *:nth-child(n+3) {
Add an element `related-event__event` and use it instead of `> *`.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/social-media-icon.scss
> +  background: url('/src/assets/filled-email-icon.svg') no-repeat center;
You can use `background-repeat` and `background-position` for `.social-media-icon`, and use `background-url` instead of background for all the modifiers.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/event-details.scss
> +  .event-details__social-media .event-details__heart-button,
Looks like the css in `@media (min-width: 750px) and (max-width: 1023px)` and `@media (min-width: 1024px)` is exactly the same, you can combine them by using `@media (min-width: 750px)`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +          <img src="/src/assets/location-icon.svg" width="8px" height="11px" alt="">
Use css `background-url` instead of the`img`.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +      <a class="header__logo "></a>
Extra space after the class name.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +            <a class="link-to__link-text" href="">Show more dates</a>
`href=javascript:void`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +            <div class="lint-to__arrow"></div>
`link-to__arrow`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/css/link-to.scss
> +.lint-to__arrow {
`link-to`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +        <div class="social-media-icon social-media-icon_is-filled-facebook"></div>
Replace the `div`s with `a` tags.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +        <img class="event-details__event-img" src="/src/assets/event-img.svg" alt="">
`img` tags should always have `alt` and `title` attributes for accessibility.

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/event.html
> +            <img class="event-card__img" src="/src/assets/big-city-life.svg" alt="">
`alt` and `title`

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/index.html
> +          <img src="/src/assets/location-icon.svg" width="8px" height="11px" alt="">
css background-url

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/index.html
> +          <a href="" class="events__chip events__chip_highlighted">Everything</a>
href="javascript;void()"

2020-02-19 01:47 UTC, khaledsayyed commented on sharqiya/src/index.html
> +                Beirut, Lebanon 4011</div>
```
              <div class="event-card__location-addr">
                 Sunflower - Douwar el Shams Beirut, Lebanon 4011
              </div>
```

2020-02-19 10:08 UTC, MohamadGT commented on sharqiya/src/css/header.scss
> +  z-index: 1;
the header should be sticky

2020-02-19 14:07 UTC, MohamadGT commented on sharqiya/src/css/header.scss
> +  &:hover {
.

2020-02-19 14:15 UTC, MohamadGT commented on sharqiya/src/css/event-card.scss
> +.event-card__event-types {
`flex-wrap: wrap`

2020-02-19 14:20 UTC, MohamadGT commented on sharqiya/src/css/related-events.scss
> +.related-event__title {
This needs a padding.

2020-02-19 14:20 UTC, MohamadGT commented on sharqiya/src/css/social-media-icon.scss
> +.social-media-icon {
We should hide this on mobile.

2020-02-19 14:22 UTC, MohamadGT commented on sharqiya/src/event.html
> +      <div class="event-details__title" itemprop="name">Night - ليل</div>
I think this needs padding-top on mobile.

2020-02-19 14:23 UTC, MohamadGT commented on sharqiya/src/event.html
> +    <a class="sub-header__back-button">
Missing `href` attribute.

2020-02-19 14:24 UTC, MohamadGT commented on sharqiya/src/css/header.scss
> +.header__browse-event {
let's hide this on tablet

2020-02-19 14:26 UTC, MohamadGT commented on sharqiya/src/css/event-details.scss
> +  margin-left: 10px;
```suggestion
  margin-right: 10px;
```

2020-02-19 14:29 UTC, MohamadGT commented on sharqiya/src/index.html
> +        <div class="header__search-icon"></div>
This should be a button.
Same for the location-icon everywhere.

2020-02-19 15:56 UTC, khaledsayyed commented on sharqiya/src/event.html
> +        <img alt="The image of this event" title="The image of this event" class="event-details__event-img" src="/src/assets/event-img.svg" alt="">
Use the same title text for `alt`.

2020-02-19 15:56 UTC, khaledsayyed approved these changes

2020-02-19 16:10 UTC, merged